using System;
using System.IO;

namespace CodeBrix.Cryptography.Utilities.Test;

/// <summary>
/// The opt-in bridge to BouncyCastle's external <c>bc-test-data</c> fixtures.
/// </summary>
/// <remarks>
/// <para>
/// Most of this suite runs against <c>test-data/</c> in this repository, which holds only
/// fixtures that are ours to redistribute: files inherited from the MIT-licensed bc-csharp
/// repository, and files generated by this library (see the TestDataGeneration folder).
/// </para>
/// <para>
/// The remainder -- NIST PKITS certificate-path data, and the post-quantum and lightweight
/// cryptography known-answer test vectors -- lives only in
/// <c>https://github.com/bcgit/bc-test-data.git</c>, a separate repository of about 4.6 GB
/// that carries no licence file. Without a licence we cannot copy those files into an
/// MIT-licensed repository, and their size would breach GitHub's limits regardless, so the
/// tests that need them are skipped by default.
/// </para>
/// <para>
/// To run them:
/// </para>
/// <list type="number">
///   <item><description>
///     Clone <c>https://github.com/bcgit/bc-test-data.git</c> so that it sits BESIDE this
///     repository -- the two directories must be siblings, for example
///     <c>~/GitHome/CodeBrix.Cryptography</c> and <c>~/GitHome/bc-test-data</c>.
///   </description></item>
///   <item><description>
///     Set <c>CODEBRIX_CRYPTOGRAPHY_USE_BC_TEST_DATA=1</c>.
///   </description></item>
/// </list>
/// <para>
/// Fixtures in this repository always take precedence, so opting in can only add files --
/// it can never change the result of a test that already passes.
/// </para>
/// </remarks>
public static class BcTestData
{
    /// <summary>The environment variable that opts into the external fixtures.</summary>
    public const string EnvironmentVariableName = "CODEBRIX_CRYPTOGRAPHY_USE_BC_TEST_DATA";

    /// <summary>The directory name looked for beside this repository.</summary>
    public const string DirectoryName = "bc-test-data";

    /// <summary>
    /// The Skip reason shared by every test that depends on the external fixtures.
    /// </summary>
    public const string SkipReason =
        "Requires the external bc-test-data fixtures, which are not redistributable and so " +
        "are not part of this repository. To run this test, clone " +
        "https://github.com/bcgit/bc-test-data.git as a SIBLING of the CodeBrix.Cryptography " +
        "directory and set CODEBRIX_CRYPTOGRAPHY_USE_BC_TEST_DATA=1.";

    private static string m_resolvedRoot;
    private static bool m_rootResolved;

    /// <summary>
    /// Whether the opt-in is set AND a sibling bc-test-data directory was actually found.
    /// Tests gated on this run only when both are true.
    /// </summary>
    public static bool IsAvailable => Root != null;

    private static bool IsOptedIn =>
        Environment.GetEnvironmentVariable(EnvironmentVariableName) == "1";

    private static string Root
    {
        get
        {
            if (!m_rootResolved)
            {
                m_resolvedRoot = IsOptedIn ? FindSiblingDirectory() : null;
                m_rootResolved = true;
            }
            return m_resolvedRoot;
        }
    }

    /// <summary>
    /// Returns the full path of a fixture inside the external checkout, or null when the
    /// opt-in is off, the checkout is absent, or the file is not there.
    /// </summary>
    internal static string ResolveOptionalResource(string relativePath)
    {
        string root = Root;
        if (root == null)
            return null;

        string path = Path.Combine(root, relativePath);
        return File.Exists(path) ? path : null;
    }

    /// <summary>
    /// Walks up from the build output looking for a sibling bc-test-data directory. This
    /// deliberate walk-up exists only behind the opt-in; the default fixture lookup in
    /// SimpleTest never leaves the repository.
    /// </summary>
    private static string FindSiblingDirectory()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            string candidate = Path.Combine(dir.FullName, DirectoryName);
            if (Directory.Exists(candidate))
                return candidate;

            dir = dir.Parent;
        }
        return null;
    }
}
